#!/bin/sh
#PBS -N {}
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=180
#PBS -q workq

JOBID=`echo $PBS_JOBID | cut -d '.' -f 1`

cd $PBS_O_WORKDIR

docker run --rm --shm-size=1g -v $PWD:/mnt -u $(id -u $USER):$(id -g $USER) cp2k/cp2k:2023.2_mpich_generic_psmp mpirun -n 90 -genv OMP_NUM_THREADS=2 cp2k -i NBBFC_cellopt.in > NBBFC_cellopt.out
