#!/bin/sh
#PBS -N Dst01
#PBS -A ...
#PBS -q workq
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=8:mpiprocs=8
#PBS -l place=free
#PBS -V

JOBID=`echo $PBS_JOBID | cut -d '.' -f 1`

cd $PBS_O_WORKDIR
cd miniconda3
conda activate /home/apparelixetsy/miniconda3/env
cd elastic
export OMP_NUM_THREADS=2
mpirun -np 4 pw.x -input Dst01_01.in > Dst01_01.out

