#!/bin/sh
#PBS -N NBBFC
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=360
#PBS -q workq

JOBID=`echo $PBS_JOBID | cut -d '.' -f 1`

cd $PBS_O_WORKDIR
docker run --rm --shm-size=1g -v $PWD:/mnt -u $(id -u $USER):$(id -g $USER) cp2k/cp2k:2024.3_mpich_generic_psmp mpirun -n 120 -genv OMP_NUM_THREADS=3 cp2k -i nbbfc-cellopt.inp > nbbfc-cellopt.out 

